### DISCUSSION TITLE
【求助】使用docker部署 微信公众号模式 但是启动后没有端口监听

### DISCUSSION THREAD

**Discussion by Lands-1203** [zhayujie/chatgpt-on-wechat#1958] [Q&A]
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/61341868/b97f6478-b2d8-4637-83d4-e9514a0d7c50)
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/61341868/99d41aa9-734b-4c88-888e-84935c701105)

**Comment by Lands-1203** [comment]
```
version: '2.0'
services:
  chatgpt-on-wechat:
    image: zhayujie/chatgpt-on-wechat
    container_name: chatgpt-on-wechat
    security_opt:
      - seccomp:unconfined
    environment:
      OPEN_AI_API_KEY: 'xxxxxx'
      OPEN_AI_API_BASE: 'https://xxxxxx.com/api'
      MODEL: 'gpt-3.5-turbo'
      PROXY: ''
      SINGLE_CHAT_PREFIX: '["bot", "@bot"]'
      SINGLE_CHAT_REPLY_PREFIX: '"[bot] "'
      GROUP_CHAT_PREFIX: '["@bot"]'
      GROUP_NAME_WHITE_LIST: '["ChatGPT测试群", "ChatGPT测试群2"]'
      IMAGE_CREATE_PREFIX: '["画", "看", "找"]'
      CONVERSATION_MAX_TOKENS: 1000
      SPEECH_RECOGNITION: 'False'
      CHARACTER_DESC: '你是ChatGPT, 一个由OpenAI训练的大型语言模型, 你旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。'
      EXPIRES_IN_SECONDS: 3600
      USE_GLOBAL_PLUGIN_CONFIG: 'True'
      USE_LINKAI: 'False'
      LINKAI_API_KEY: ''
      LINKAI_APP_CODE: ''
      
       # wechatmp的配置
      channel_type: "wechatmp" 
      wechatmp_token: 'xxxxxx' # 微信公众平台的Token
      wechatmp_port: 8080  # 微信公众平台的端口需要端口转发到80或443
      wechatmp_app_id: 'xxxxxx'  # 微信公众平台的appID
      wechatmp_app_secret: 'xxxxxx'  # 微信公众平台的appsecret
      wechatmp_aes_key: 'xxxxxx'  # 微信公众平台的EncodingAESKey，加密模式需要	

```
