### DISCUSSION TITLE
搭建docker环境如果在国外主机可能提示dns解析失败的解决办法

### DISCUSSION THREAD

**Discussion by skinnyshy** [zhayujie/chatgpt-on-wechat#2069] [Q&A]
### 问题描述
启动服务后docker logs -f chatgpt-on-wechat后日志告警
```shel
Failed to resolve 'qyapi.weixin.qq.com'
```
并且无法收到消息
### 解决方法
可以通过修改docker-compose.yaml文件为容器指定dns服务器
```yaml
version: '2.0'
services:
  chatgpt-on-wechat:
    image: zhayujie/chatgpt-on-wechat
    dns: [223.5.5.5, 223.6.6.6] # 指定为国内dns
    container_name: chatgpt-on-wechat
...
```

然后删除重启容器
```shel
docker-compose down
docker-compose up -d
```
