### ISSUE TITLE
能否增加对第三方的OpenAI API Key的支持（除Azure以外）

### ISSUE THREAD

**Issue by powerliu2020** [zhayujie/chatgpt-on-wechat#1917]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

能否增加对除了Azure以外的第三方openai api key的支持。

例如https://openrouter.ai/，但需要可以自定义open_ai_api_base，而目前只支持Azure的Openai key

### 动机

openai官方太容易封号，所以借助第三方的api key连接chatGPT更稳定些

**Comment by liuyz0112** [comment]
同求

**Comment by chenbe1990** [comment]
本来就支持啊。

**Comment by liuyz0112** [comment]
@chenbe1990 请问可以看下你的配置吗，我捣鼓了好久没成功，用的docker-compose

**Comment by liangxuannb** [comment]
所以open_ai_key_base是干啥的？？？

**Comment by liuyz0112** [comment]
@liangxuannb 我尝试过了，好像没用

```
version: '2.0'
services:
  chatgpt-on-wechat:
    image: zhayujie/chatgpt-on-wechat
    container_name: chatgpt-on-wechat
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./config.json:/app/plugins/config.json
    environment:
      OPEN_AI_API_KEY: 'sk-xxxxxx'
      MODEL: 'gpt-3.5-turbo'
      open_ai_key_base: '8.0.0.0:3000'
      PROXY: ''
      SINGLE_CHAT_PREFIX: '["bot", "@bot"]'
      SINGLE_CHAT_REPLY_PREFIX: '"[bot] "'
      GROUP_CHAT_PREFIX: '["@bot"]'
      GROUP_NAME_WHITE_LIST: '["ChatGPT测试群", "ChatGPT测试群2"]'
      IMAGE_CREATE_PREFIX: '["画", "看", "找"]'
      CONVERSATION_MAX_TOKENS: 1000
      SPEECH_RECOGNITION: 'False'
      CHARACTER_DESC: '你是ChatGPT, 一个由OpenAI训练的大型语言模型, 你旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。'
      EXPIRES_IN_SECONDS: 3600
      USE_GLOBAL_PLUGIN_CONFIG: 'True'
      USE_LINKAI: 'False'
      LINKAI_API_KEY: ''
      LINKAI_APP_CODE: ''

```
