### ISSUE TITLE
docker版本下的 USE_LINKAI 参数无效，导致 linkai 插件无法使用知识库提问

### ISSUE THREAD

**Issue by 1-bytes** [zhayujie/chatgpt-on-wechat#2350]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

docker-compose.yml文件内容如下（已脱敏处理）：

```
version: '2.0'
services:
  chatgpt-on-wechat:
    image: zhayujie/chatgpt-on-wechat
    container_name: chatgpt-on-wechat
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./plugins:/app/plugins
    environment:
      OPEN_AI_API_BASE: 'https://apic.ohmygpt.com/v1'
      OPEN_AI_API_KEY: 'sk-Dxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx56'
      BOT_TYPE: 'chatGPT'
      MODEL: 'claude-3-5-sonnet-20241022'
      PROXY: ''
      TEXT_TO_IMAGE: 'dall-e-3'
      VOICE_TO_TEXT: 'openai'
      TEXT_TO_VOICE: 'openai'
      TEXT_TO_VOICE_MODEL: 'tts-1'
      TTS_VOICE_ID: 'alloy'
      SINGLE_CHAT_PREFIX: '[""]'
      SINGLE_CHAT_REPLY_PREFIX: '""'
      NO_NEED_AT: 'True'
      GROUP_CHAT_PREFIX: '["@bot", "@Bot", "@BOT"]'
      GROUP_NAME_WHITE_LIST: '["ALL_GROUP"]'
      GROUP_CHAT_IN_ONE_SESSION: '[""]'
      CONVERSATION_MAX_TOKENS: 3000
      IMAGE_CREATE_PREFIX: '["画", "看", "找"]'
      CLEAR_MEMORY_COMMANDS: '["#清除记忆", "#重置", "#new", "#NEW", "#New", "#清除"]'
      SPEECH_RECOGNITION: 'True'
      GROUP_SPEECH_RECOGNITION: 'True'
      VOICE_REPLY_VOICE: 'True'
      ALWAYS_REPLY_VOICE: 'False'
      HOT_RELOAD: 'True'
      CHARACTER_DESC: '你是基于大语言模型的AI智能助手，旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流，请注意你只能使用纯文本响应回复，禁止使用 Markdown 格式响应回复.'
      EXPIRES_IN_SECONDS: 3600
      TEMPERATURE: 0.5
      USE_GLOBAL_PLUGIN_CONFIG: 'True'
      USE_LINKAI: 'True'
      LINKAI_API_KEY: 'Link_xxxxxxxxxxxxxxxxxxxxxxx'
      LINKAI_APP_CODE: 'WUY87LNQ'
```

./plugins/config.json 文件的内容如下：
```
{
    "godcmd": {
        "password": "123456",
        "admin_users": [
        ]
    },
    "apilot": {
        "alapi_token": "xxxxxxxxxxxxxxxxx",
        "morning_news_text_enabled": true
    },
    "linkai": {
        "group_app_map": {
            "YL的小窝": "Kv2fXJcH"
        },
        "midjourney": {
            "enabled": true,
            "auto_translate": true,
            "img_proxy": false,
            "max_tasks": 5,
            "max_tasks_per_user": 1,
            "use_image_create_prefix": true
        },
        "summary": {
            "enabled": true,
            "group_enabled": true,
            "max_file_size": 5000,
            "type": [
                "FILE",
                "SHARING"
            ]
        }
    }
}
```

先启用 linkai 插件

我先在群里执行了这个，手动指定了一个app code：
@bot $linkai app Kv2fXJcH

然后又开启了群聊天：
@bot $linkai open

然后提问：

- 现在几点了？
- 帮我搜索小米su7的参数
- 你是谁？

....
等问题，依然走的是openai

但是mj画图是走的linkai api接口，可以在 linkai 官网观察到调用情况。

在 linkai 的应用广场选择了其他的 app code填进来重复上面的步骤，依然没效果

docker日志里面没有任何报错，linkai 也加载上了

<img width="633" alt="Xnip2024-10-24_05-08-28" src="https://github.com/user-attachments/assets/dc4e08de-f4ec-4eb6-a0b7-220f1785b396">

<img width="1275" alt="Xnip2024-10-24_05-09-31" src="https://github.com/user-attachments/assets/daebcbf9-7aeb-4bb1-ad4e-b9c4b85636df">
