### ISSUE TITLE
钉钉部署问题

### ISSUE THREAD

**Issue by 985154457** [zhayujie/chatgpt-on-wechat#2512]
### 前置确认

- [x] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [x] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

other

### 问题描述 😯

部署过程时，Steam推送模式无法正常接入

### 终端日志 📒

services:
  chatgpt-on-wechat:
    image: zhayujie/chatgpt-on-wechat
    container_name: chatgpt-on-wechat
    security_opt:
      - seccomp:unconfined
    environment:
      TZ: 'Asia/Shanghai'
      OPEN_AI_API_KEY: ''
      MODEL: 'deepseek-reasoner'
      PROXY: ''
      SINGLE_CHAT_PREFIX: '["bot", "@bot"]'
      SINGLE_CHAT_REPLY_PREFIX: '"[bot] "'
      GROUP_CHAT_PREFIX: '["@bot"]'
      GROUP_NAME_WHITE_LIST: '["ChatGPT测试群", "ChatGPT测试群2"]'
      IMAGE_CREATE_PREFIX: '["画", "看", "找"]'
      CONVERSATION_MAX_TOKENS: 1000
      SPEECH_RECOGNITION: 'False'
      CHARACTER_DESC: '你是ChatGPT, 一个由OpenAI训练的大型语言模型, 你旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。'
      EXPIRES_IN_SECONDS: 3600
      USE_GLOBAL_PLUGIN_CONFIG: 'True'
      USE_LINKAI: 'False'
      LINKAI_API_KEY: ''
      LINKAI_APP_CODE: ''
      LINKAI_CONFIG: '{"channel_type": "dingtalk", "dingtalk_client_id": "", "dingtalk_client_secret": ""}'

**Comment by 985154457** [comment]
可能是yaml文件有关钉钉的内容写的不对

**Comment by 200928** [comment]
试试下面的 yaml 配置，小心敏感信息
```yaml
services:
  chatgpt-on-wechat:
    image: zhayujie/chatgpt-on-wechat
    container_name: chatgpt-on-wechat
    security_opt:
      - seccomp:unconfined
    environment:
      TZ: "Asia/Shanghai"
      OPEN_AI_API_KEY: "xxx"
      open_ai_api_base: "https://api.openai-proxy.org"
      MODEL: "deepseek-reasoner"
      PROXY: ""
      SINGLE_CHAT_PREFIX: '["bot", "@bot"]'
      SINGLE_CHAT_REPLY_PREFIX: '"[bot] "'
      GROUP_CHAT_PREFIX: '["@bot"]'
      GROUP_NAME_WHITE_LIST: '["ChatGPT测试群", "ChatGPT测试群2"]'
      IMAGE_CREATE_PREFIX: '["画", "看", "找"]'
      CONVERSATION_MAX_TOKENS: 1000
      SPEECH_RECOGNITION: "False"
      CHARACTER_DESC: "你是ChatGPT, 一个由OpenAI训练的大型语言模型, 你旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。"
      EXPIRES_IN_SECONDS: 3600
      USE_GLOBAL_PLUGIN_CONFIG: "True"
      USE_LINKAI: "False"
      LINKAI_API_KEY: ""
      LINKAI_APP_CODE: ""
      channel_type: "dingtalk"
      dingtalk_client_id: "xxx"
      dingtalk_client_secret: "xxx"

```
